### ISSUE TITLE
求项目演示的URL传送门

### ISSUE THREAD

**Issue by Ezoio** [BlueSky-07/cilicili#1]

**Comment by BlueSky-07** [comment]
这个项目功能包含视频上传，可能有版权、审查等问题，所以不提供线上演示。
按照这个 [说明](../blob/master/README.md#user-content-4-%E5%AE%89%E8%A3%85--%E8%BF%90%E8%A1%8C) 操作即可在本地运行。
以后有空的话可能会做个 Docker 镜像。
